typography_spectrum: 0.5219216
color:
  saturation: 0.6040112
  brandStrength: 0.2600247
  rhythmicContrast: 0.4860075
  lightness: 0.9029851
layout_spectrum: 0.9575725
name: Garrett Ruhland
navigation:
  - name: Nootropics
    id: e06cc1b0-e25a-43ee-bf04-2b18785a485f
    type: content
  - name: Professional Experience
    id: 67c80820-3ac3-4bc5-9e52-c96ae975a176
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
