layout_spectrum: 0.07571202
color:
  saturation: 0.5240048
  lightness: 0.1830201
  brandStrength: 0.2600247
  rhythmicContrast: 0.5919121
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.5219216
name: Garrett Ruhland
